apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
spec:
  serviceName: "stateful-service-mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: arm64v8/mysql:oracle
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
